### PR TITLE
Add support for interactive legends

### LINKED ISSUE #2274: Interactive Legends
Placeholder for tracking, discussion, and eventual roamap inclusion regarding interactive legends.

Three wishlist items for legends that are common in other JS plotting libraries:
1) Legends off the plot area
2) Hover over legend item and respective glyphs highlight in plot
3) Click of legend item hides/shows the respective glyphs

Use cases include data identification for those with color blindness

Original discussion: https://groups.google.com/a/continuum.io/d/msg/bokeh/TymlMcwsZH0/Fs9Wpxle8SwJ

### PR DESCRIPTION
**Pull request by mattpap**
This allows for clickable legends. Try `examples/models/synthetic`, which was designed to outline issues with event handling and propagation, so it's perfect to test this. For example, currently clicking on a legend doesn't prevent from making selection if there's a glyph underneath.

fixes #2274, #3715

### CODE REVIEW

**Comment by birdsarah** [comment]
@mattpap, i was happy with the functionality in this PR. Can we get this merged?

File: bokeh/models/annotations.py [hunk 1]
```diff
@@ -120,10 +120,24 @@ class Legend(Annotation):
...
 
+    inactive_props = Include(FillProps, help="""
+    The %s for the legend background style when inactive.
+    """)
+
+    hover_props = Include(FillProps, help="""
+    The %s for the legend background style when hovered.
+    """)
+
+    click_policy = Enum("hide", "mute")
```
Comment (bryevdv) [inline bokeh/models/annotations.py]: This can be documented better if it is a defined enum in the python enums module.

File: bokeh/models/renderers.py [hunk 2]
```diff
@@ -145,6 +145,12 @@ def _check_bad_column_name(self):
     being hovered over by a HoverTool.
     """)
 
+    mute_glyph = Instance(Glyph, help="""
```
Comment (bryevdv) [inline bokeh/models/renderers.py]: woudl prefer `muted_glyph`

Comment (mattpap) [inline bokeh/models/renderers.py]: I chose `mute` over `muted` because the later doesn't follow the convention. Otherwise we would have `selected_glyph`, `hovered_glyph`, etc.

**Comment by bryevdv** [comment]
I understand what you mean about moving some thing further away from tools. I think it's ok to merge for now, a larger rework should be a separate effort.

**Comment by bryevdv** [comment]
@mattpap this is ready to do? Do you want to merge the fix in master in first, or just merge as-is?

**Comment by bryevdv** [comment]
I went ahead and merged master, let's get it green.

**Comment by bryevdv** [comment]
Hrm, after the merge one unit test fails:
```
E       AssertionError: Extra properties: click_policy, hover_fill_alpha, hover_fill_color, inactive_fill_alpha, inactive_fill_color
```

**Comment by bryevdv** [comment]
I updated the test, should go green now.

**Comment by bryevdv** [comment]
@birdsarah @mattpap OK after testing this out on some examples. I did want to bring one thing to attention tho. For the "original" style legends this works great. When the legend is a field (e.g. the gapminder app example) then currently clicking any legend row turns off *all* legend rows. This is not too surprising. So my question is just to confirm that that behavior is OK to start with (with a release note) and second, I think there should be another `click_policy` added: `"none"` and maybe this should actually be the default (i.e. preserve existing default behaviour?)

**Comment by bryevdv** [comment]
@birdsarah the selenium errors are things like:
```
Message: window.get_x_range_end is not a function
```
Could this be a changed version of something causing test problems? (would be third one today!)

**Comment by mattpap** [comment]
> (...) there should be another click_policy added: "none" (...)

I had the same thought today when debugging some user code.

**Comment by mattpap** [comment]
> `Message: window.get_x_range_end is not a function`

This is how selenium tests work. Most likely there is some JavaScript error before that.

**Comment by bryevdv** [comment]
> This is how selenium tests work. Most likely there is some JavaScript error before that.

OK I will leave this in your hands :)

**Comment by mattpap** [comment]
I'm not sure if this is some sort of race condition, but locally those tests don't show any errors.

**Comment by bryevdv** [comment]
Fixed the merge conflict, which was just the added `return null` from another PR. @mattpap please re-pull

**Comment by birdsarah** [comment]
>  click_policy added: "none" and maybe this should actually be the default (i.e. preserve existing default behaviour?)

Yes - I think it's better, especially in the short term, if the default is the current behavior and you have the option of turning on the clickable legends.

**Comment by mattpap** [comment]
I think this should be rescheduled for 0.14.5 and merged just after 0.14.4 release.

**Comment by bryevdv** [comment]
I'm OK with that, @birdsarah would that impact your work?

File: examples/models/synthetic.py [hunk 3]
```diff
@@ -0,0 +1,89 @@
...
+
+doc = Document()
+doc.add_root(plot)
+
+if __name__ == "__main__":
+    filename = "synthetic.html"
+    with open(filename, "w") as f:
+        f.write(file_html(doc, INLINE, "A synthetic example"))
+    print("Wrote %s" % filename)
+    view(filename)
```
Comment (bryevdv) [inline examples/models/synthetic.py]: This example is confusing with so many legends. I agree there is a reason for the "legends" example to have so many (to show off how/where to have legends) but in this example it will only confuse users. By far the common use case users will have is a single interactive legend, and so that is what we should demonstrate. It would be good to add a `plotting` example` too, maybe just adding an interactive legend to the stocks one or the iris one.

Comment (bryevdv) [inline examples/models/synthetic.py]: This example is also confusing because the legend "red circles" don't obviously correspond to some particular set of data on the plot. What people want is "click the blue line in the legend and the corresponding blue line in the plot disappears"

**Comment by bryevdv** [comment]
@mattpap I only have a comment about the example(s). Also, IIRC this will not work with recent "grouped" renderer usage, correct? (i.e. when a legend is asked to be pulled from a column) If so that should be documented.

File: examples/models/synthetic.py (hunk 3 above)
Comment (mattpap) [inline examples/models/synthetic.py]: @bryevdv, this is a "synthetic" example that's designed to explore bokeh's functionality. I expect this class of examples to turn into integration tests, but the infrastructure is broken, so this will have to wait. Perhaps there could be another directory added under `examples/`. A proper example showing off this new feature should be added or an existing modified.

**Comment by mattpap** [comment]
> Also, IIRC this will not work with recent "grouped" renderer usage, correct?

I don't exactly follow how this feature works, so it may not work together with this PR.

**Comment by mattpap** [comment]
> Actually there should definitely be a section added to the user's guide with an example.

I would be great if you could add this. Perhaps this and dealing with `synthetic.py` example could be done in a followup PR, so that we don't block other work.

**Comment by bryevdv** [comment]
> I would be great if you could add this. Perhaps this and dealing with synthetic.py example could be done in a followup PR, so that we don't block other work.

I have a client call in a few hours. I will add a simple example under `plotting/file` and add user guide docs immediately after, then merge this this afternoon.

File: bokeh/plotting/helpers.py [hunk 4]
```diff
@@ -552,15 +552,23 @@ def func(self, **kwargs):
         else:
             hglyph_ca = None
 
+        # handle the mute glyph, if any properties were given
+        if any(x.startswith('mute_') for x in kwargs):
+            mglyph_ca = _pop_colors_and_alpha(glyphclass, kwargs, prefix='mute_')
+        else:
+            mglyph_ca = None
+
```
Comment (bryevdv) [inline bokeh/plotting/helpers.py]: @mattpap just a heads up I am going to change this to `muted_` when I push docs changes

**Comment by bryevdv** [comment]
added new doc and example, will merge when green.

**Comment by bryevdv** [comment]
@mattpap hover fill props are not actually used?

**Comment by mattpap** [comment]
> hover fill props on legend are not actually used?

They were supposed to be used, but implementing hover for legends wasn't feasible at this point, because every change in hover would require redrawing a plot (event if not requested).

**Comment by bryevdv** [comment]
So they should be removed for now?

**Comment by birdsarah** [comment]
WOOOOOT :D

**Comment by guillochon** [comment]
Glad this has been added! For me, since I am currently drawing points/errorbars as two separate sets of glyps, the hiding only half works, but I am guessing this functionality will work with the upcoming `FilledArea`/`Whisker`/`Stem` classes?

**Comment by bryevdv** [comment]
@guillochon there's nothing built in. There might be a workaround using he new generic events, I'm not certain. It's a perfectly reasonable feature but it also never entered my mind, so I'd suggest explicitly calling it out in the error bars issue so that its taken into account there.
