### PR TITLE
Fix Django Integration

### LINKED ISSUE #10800: Upgrade bokeh.server.django to django 3.x
### FOLLOW THESE INSTRUCTIONS CAREFULLY

*ISSUES THAT DO NOT CONTAIN NECESSARY INFORMATION MAY BE CLOSED, IMMEDIATELY*

The issue tracker is NOT the place for general support. For questions and technical assistance, come join the [Bokeh  Project Discourse](https://discourse.bokeh.org).

For defects or deficiencies, please provide *ALL OF THE FOLLOWING*:

#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)

Ubuntu 20.04
python 3.8.5
bokeh-2.2.3, Django-3.1.4, channels-3.0.3, panel-0.10.2
Firefox 84.0
Chrome 87.0.4280.66

#### Description of expected behavior and the observed behavior

Trying to run your bokeh django howto code located [here](https://github.com/bokeh/bokeh/tree/branch-2.3/examples/howto/server_embed/django_embed).

When I run `python3 manage.py runserver 0.0.0.0:8000` the server starts without any issues.

When I then go to any of the app links:
[http://127.0.0.1:8000/shape_viewer](http://127.0.0.1:8000/shape_viewer), [http://127.0.0.1:8000/sea_surface](http://127.0.0.1:8000/sea_surface), or [http://127.0.0.1:8000/sea_surface_with_template](http://127.0.0.1:8000/sea_surface_with_template)
The tab says: '500 Internal Server Error Exception inside application. Daphne'

#### Complete, minimal, self-contained example code that reproduces the issue

```
# code goes here between backticks

python3 manage.py runserver 0.0.0.0:8000

```

#### Stack traceback and/or browser JavaScript console output
```Traceback (most recent call last):
  File "Directory/lib/python3.8/site-packages/channels/routing.py", line 71, in __call__
    return await application(scope, receive, send)
  File "Directory/lib/python3.8/site-packages/channels/sessions.py", line 47, in __call__
    return await self.inner(dict(scope, cookies=cookies), receive, send)
  File "Directory/lib/python3.8/site-packages/channels/sessions.py", line 254, in __call__
    return await self.inner(wrapper.scope, receive, wrapper.send)
  File "Directory/lib/python3.8/site-packages/channels/auth.py", line 181, in __call__
    return await super().__call__(scope, receive, send)
  File "Directory/lib/python3.8/site-packages/channels/middleware.py", line 26, in __call__
    return await self.inner(scope, receive, send)
  File "Directory/lib/python3.8/site-packages/channels/routing.py", line 150, in __call__
    return await application(
  File "Directory/lib/python3.8/site-packages/asgiref/compatibility.py", line 33, in new_application
    instance = application(scope)
  File "Directory/lib/python3.8/site-packages/bokeh/server/django/consumers.py", line 103, in __init__
    kwargs = self.scope["url_route"]["kwargs"]
AttributeError: 'DocConsumer' object has no attribute 'scope'
HTTP GET /shape_viewer 500 [0.90, 127.0.0.1:56486]
```

### LINKED ISSUE #11148: Update `bokeh.server.django` to work with Django 3.2
bokeh==2.3.1
Django==3.2

#### Description of expected behavior and the observed behavior
bokeh.server.django works with Django 3.2

#### Complete, minimal, self-contained example code that reproduces the issue
In a Django 3.2 project, in <project_name>/settings.py:

```
INSTALLED_APPS = [
         'bokeh.server.django',
        ]
```

Then run 

```
python manage.py shell
```
#### Stack traceback and/or browser JavaScript console output

Traceback (most recent call last):
  File "manage.py", line 21, in <module>
    main()
  File "manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/home/ejprinz/code/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/home/ejprinz/code/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 395, in execute
    django.setup()
  File "/home/ejprinz/code/venv/lib/python3.8/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/ejprinz/code/venv/lib/python3.8/site-packages/django/apps/registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "/home/ejprinz/code/venv/lib/python3.8/site-packages/django/apps/config.py", line 255, in create
    return app_config_class(app_name, app_module)
  File "/home/ejprinz/code/venv/lib/python3.8/site-packages/django/apps/config.py", line 38, in __init__
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: The app label 'bokeh.server.django' is not a valid Python identifier.

The root cause is that Django 3.2 now checks that app labels are identifiers. This is done in the file
...site-packages/django/apps/config.py, line 37-40:

```
        if not self.label.isidentifier():
            raise ImproperlyConfigured(
                "The app label '%s' is not a valid Python identifier." % self.label
            )
```

So, "bokeh.server.django" is not a valid identifier. An easy fix for bokeh is to change one line in
site-packages/bokeh/server/django/apps.py

Replace line 41 by:
```
    name = 'bokeh.server.django'
    label = 'bokeh_server_django'
```

With this fix Django 3.2 works again with Bokeh, but in the users' code, the calls to:
```
apps.get_app_config('bokeh.server.django')
```
have to be replaced by:
```
apps.get_app_config('bokeh_server_django')
```
which is not a big deal but should be mentioned in the release notes.

### LINKED ISSUE #11924: [BUG] Incompatibility with Django 4.0
### Software versions

Python version      :  3.9.2 (default, Feb 28 2021, 17:03:44) 
IPython version     :  7.20.0
Tornado version     :  6.1
Bokeh version       :  2.4.2
BokehJS static path :  /usr/local/lib/python3.9/dist-packages/bokeh/server/static
node.js version     :  (not installed)
npm version         :  (not installed)
Operating system    :  Linux-5.10.0-9-amd64-x86_64-with-glibc2.31

### Browser name and version

_No response_

### Jupyter notebook / Jupyter Lab version

_No response_

### Expected behavior

Compatibility of Bokeh with most recent Django 4.0

### Observed behavior

Using Bokeh 2.4.2 with Django 4.0 leads to the following error message on Django startup: 

...
 File "/usr/local/lib/python3.9/dist-packages/bokeh/server/django/routing.py", line 27, in <module>
    from django.conf.urls import url
ImportError: cannot import name 'url' from 'django.conf.urls' (/usr/local/lib/python3.9/dist-packages/django/conf/urls/__init__.py)

It seems to be related to https://forum.djangoproject.com/t/django-4-0-url-import-error/11065 - i.e. deprecation of url() function in Django 3.1 and its removal in Django 4.0

### Example code

```Python
The code in routing.py should be changed, i.e. Bokeh file bokeh/server/django/routing.py should be corrected:

line 27:
from django.conf.urls import url
into
from django.urls import re_path

lines 108, 123, 125 and 127:
url(...
into
re_path(...

(no example code is available as this problem is triggered directly by a Bokeh distribution file on Django startup, the above (manual) changes in my local Bokeh installation led to Django startup without the above error message).
```

### Stack traceback or browser console output

_No response_

### Screenshots

_No response_

### PR DESCRIPTION
**Pull request by sdc50**
updates django consumers and routing to be compatible with django 2.x-4.x

This should address issues #11924, #11148, and #10800.

I have discussed with @philippjfr about breaking out the django integration code into it's own repository, but I just wanted to submit this in case there was interest in patching this in Bokeh 2.4 before the 3.0 release.

fixes #11924 
fixes #11148 
fixes #10800

### CODE REVIEW

**Comment by mattpap** [comment]
Currently we don't have intention to make any new 2.4 releases, so I would rebase this on `branch-3.0` and change the base branch in this PR. If we change our mind about this, then we can backport this change to 2.4.

**Comment by mattpap** [comment]
Also, on a side note, we would first need to update `branch-2.4` to allow tests to pass.

**Comment by philippjfr** [comment]
>Currently we don't have intention to make any new 2.4 releases, so I would rebase this on branch-3.0 and change the base branch in this PR. If we change our mind about this, then we can backport this change to 2.4.

Was going to bring this PR and the plan around the Django integration up at today's meeting. I agree that we should target this fix at the 3.0 branch and backport it to 2.4 if we decide to make a patch release. Even if we decide to remove the django integration in bokeh 3.0 and move it to a separate repo I think it would still be fine to merge this fix first.

**Comment by mattpap** [comment]
I rebased this onto `branch-3.0` and attempted to make it work. Now it can start, but hangs on examples.

**Comment by mattpap** [comment]
Note that testing this, one needs panel updated to bokeh 3.0 (there's a PR for that, but it requires further changes).

**Comment by stonebig** [comment]
this problem hearts a little bit with Django-4.0.x. What is the expected release horizon of Bokeh-3.0 ? summer 2022 ?

**Comment by bryevdv** [comment]
@philippjfr what should be the plan here?

**Comment by mattpap** [comment]
This PR is obsolete given the move of django integration code to the new [bokeh-django](https://github.com/bokeh/bokeh-django) repository.
