### PR TITLE
Expose desired_num_ticks on tickers

### LINKED ISSUE #2185: Allow users to specify a desired number of ticks
Expose `desired_num_ticks` on on the ticker base class, and expose it to python models. Note, this value is a *suggestion* and tickers may ignore it, if it is not applicable (i.e., or single interval tickers), or use it merely as a soft goal (e.g. adaptive ticker)

### PR DESCRIPTION
**Pull request by bryevdv**
issues: fixes #2185

Exposes `desired_num_ticks` on ticker objects to allow users to suggest
a target number of ticks. Adds an example of use in:

https://github.com/bokeh/bokeh/blob/feature/2185_num_ticks/examples/plotting/file/line.py

### CODE REVIEW

**Comment by bryevdv** [comment]
screen shot 2015-04-18 at 3 43 41 pm

**Comment by bryevdv** [comment]
Small PR in response to mailing list question, this was simple and should have been exposed since the beginning. @bokeh/dev ready for review

**Comment by almarklein** [comment]
Just thinking out loud, but would it make sense to allow specifying some form of "tick density" or "approximate #pixels between ticks"? Absolute number of ticks does not hold up very well when the figure is scaled very small or large. I suppose it also depends on the use case?

**Comment by bryevdv** [comment]
@almarklein here are lots of noted issues around ticking improvements, see #1668 As noted in the dic, this is not really an absolute number of ticks, it is s a rough suggestion. The basic ticker will always pick "nice" numbers, for instance, and the single interval ticker will always tick at multiples of a single interval. Are you saying that "num ticks" does not hold up at large/small scales because the ticket labels may grow to be long? I can't think of any other difference that scale could make. In the short term tick labels can be rotated, in the long term, accounting for tick label text length is one of the sub-issues for #1668 I put this one in because there is currently *no* control over the number of ticks, and this could be exposed very quickly.

**Comment by bryevdv** [comment]
@bokeh/core BTW would like to merge this today, before a dev build unless there are objections.

**Comment by fpliger** [comment]
LGTM

**Comment by esvhd** [comment]
Hi - the link to the example of use at the top of this page is no longer available. Can I find this anywhere? 

Thanks.

**Comment by damianavila** [comment]
Should be here: https://github.com/bokeh/bokeh/blob/master/examples/plotting/file/line.py

**Comment by bryevdv** [comment]
@esvhd the link was to the old PR branch, I've updated it to point to master which is where the example is now.

**Comment by esvhd** [comment]
Thanks, it works like a charm!

**Comment by pabarber** [comment]
Hi there. The links noted here do not seem to be working. Can you update so people can find the solution to this?

**Comment by damianavila** [comment]
@pabarber, you have here: https://github.com/bokeh/bokeh/blob/master/examples/plotting/file/custom_datetime_axis.py#L51, one example using `desired_num_ticks`.

**Comment by pabarber** [comment]
Great. Many thanks.

**Comment by rt0161** [comment]
> Should be here: https://github.com/bokeh/bokeh/blob/master/examples/plotting/file/line.py

page not found

**Comment by bryevdv** [comment]
It's set like every other Bokeh property, an attribute on the object you want to control:

```
p.xaxis.ticker.desired_num_ticks
```

**Comment by gshpychka** [comment]
> It's set like every other Bokeh property, an attribute on the object you want to control:
> 
> ```
> p.xaxis.ticker.desired_num_ticks = 5
> ```

This throws an AttributeError:

'''
AttributeError: '_list_attr_splat' object has no attribute 'ticker'
'''

**Comment by bryevdv** [comment]
@gshpychka the above code works with Bokeh >= 1.4. For earlier versions you will need to be explicit about indexing `p.xaxis` since there can be multiple x-axes, e.g.

p.xaxis[0].ticker.desired_num_ticks = 5
