### ISSUE TITLE
Update core/dom.ts to work with upcoming TypeScript 2.3.0

### ISSUE THREAD

**Issue by mattpap** [bokeh/bokeh#6124]
Fails with:
```
src/coffee/core/dom.ts(13,15): error TS2352: Type 'DocumentFragment' cannot be converted to type 'HTMLElement'.
```
