### ISSUE TITLE
CONTRIBUTING.md Code Issue

### ISSUE THREAD

**Issue by mjharrigan** [bokeh/bokeh#3947]
The below line found in the contributing section does not work on my version - bokeh (0.11.1) with Python 3.
```
python -c "import bokeh; print(bokeh.print_versions())"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: module 'bokeh' has no attribute 'print_versions'
```

**Comment by bryevdv** [comment]
@mjharrigan good catch this is just `bokeh.__version__` which is more standard for libraries AFAIK. There's actually a few things out of date with https://github.com/bokeh/bokeh/blob/master/CONTRIBUTING.md thanks for bringing it to our attention.
