### ISSUE TITLE
Bokeh application note doesn't work in jupyter

### ISSUE THREAD

**Issue by zjffdu** [bokeh/bokeh#6451]
For defects or deficiencies, please provide ALL OF THE FOLLOWING:

Reported in https://github.com/bokeh/bokeh/pull/5886#issuecomment-280671299

#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)

bokeh: 0.12.6dev2
python: 3.5
notebook: jupyter

#### Description of expected behavior and the observed behavior
https://github.com/ecerami/pydata-essentials/blob/master/bokeh/bokeh_notebook_embed.ipynb works in bokeh 0.12.5, but doesn't owrk in 0.12.6dev2

#### Complete, minimal, self-contained example code that reproduces the issue
https://github.com/ecerami/pydata-essentials/blob/master/bokeh/bokeh_notebook_embed.ipynb

#### Stack traceback and/or browser JavaScript console output

```
works with bokeh 0.12.5; 0.12.6rc4 fails with the error:

AttributeError Traceback (most recent call last)
in ()
45
46 doc = app.create_document()
---> 47 show(app, notebook_url="localhost:8888")

/local1/anaconda2/lib/python2.7/site-packages/bokeh/io.pyc in show(obj, browser, new, notebook_handle, notebook_url)
282 # in Tornado) just in order to show a non-server object
283 if getattr(obj, '_is_a_bokeh_application_class', False):
--> 284 return _show_notebook_app_with_state(obj, _state, "/", notebook_url)
285
286 if obj not in _state.document.roots:

/local1/anaconda2/lib/python2.7/site-packages/bokeh/io.pyc in _show_notebook_app_with_state(app, state, app_path, notebook_url)
289
290 def _show_notebook_app_with_state(app, state, app_path, notebook_url):
--> 291 if state.notebook_type == 'zeppelin':
292 raise ValueError("Zeppelin doesn't support show bokeh app.")
293

/local1/anaconda2/lib/python2.7/site-packages/bokeh/core/state.pyc in notebook_type(self)
89
90 '''
---> 91 return self._notebook_type
92
93 @notebook_type.setter

AttributeError: 'State' object has no attribute '_notebook_type'
```

**Comment by bryevdv** [comment]
Why does the built in example notebook work fine, and this one does not?

**Comment by bryevdv** [comment]
Answer: this notebook does not call `output_notebook`

**Comment by bryevdv** [comment]
It's possible we can make a better error message in this instance, but let's make a new issue for that.
