### ISSUE TITLE
Create optional bundle for IonRangeSlider from the examples

### ISSUE THREAD

**Issue by Karel-van-de-Plassche** [bokeh/bokeh#7852]
Create an optional bundle for the IonRangeSlider, as discussed in https://github.com/bokeh/bokeh/pull/7850#issuecomment-385771880. Relevant snips:

> I would say ionRangeSlider is definitely a better slider in almost all respects than noUiSlider, in terms of appearance, configurability, and features, with the sole exception of lacking a vertical orientation. Unfortunately I don't really think we can replace it as the default slider at this point, but I would not be against adding at as another optional bundle so that users don't have to resort to copy and pasting a custom extension just to use it.

> I doubt there is much by way of documentation on this, it's somewhat tied to our build/release process which has mostly only involved a couple of people. That said perhaps this is an opportunity to improve the dev docs. In terms of previous models, you can look to how the bokeh tables widgets bundle was split off.

> Well, that happened in this PR, which was unfortunately rather large, but individual commits may point to how it worked to split things up: #6335

**Comment by Karel-van-de-Plassche** [comment]
I'm calling it a day for today.

Spend today reading and looking into the bokeh structure. I've never written TypeScript before (also no JavaScript..) so I'm sure my code will need a lot of checking and refactoring. I've initialized a folder and file structure in the 'contrib' style, but a permanent solution will have to be found in #7853.

I tried to make it a bit stand-alone, so I did not extend `AbstractSlider`. Instead, I copied heavily from it and mashed it together with my https://github.com/Karel-van-de-Plassche/bokeh_ion_range_slider. The result can be found here https://github.com/Karel-van-de-Plassche/bokeh/commit/07a10ab0b30f3206a29f66b28314ddebd58b3ac2.

My current example builds (`python setup.py develop --build-js`) and the JS tests pass (`py.test -m js`) , but `python ./examples/models/file/ion_range_sliders.py` currently show a blank screen. Note to future me:

```
Uncaught Error: Model 'IonRangeSlider' does not exist. This could be due to a widget
                     or a custom model not being registered before first usage.
    at Object.i.Models (ion_range_sliders.html:26)
    at Function.t._instantiate_object (ion_range_sliders.html:26)
    at Function.t._instantiate_references_json (ion_range_sliders.html:26)
    at Function.t.from_json (ion_range_sliders.html:26)
    at ion_range_sliders.html:26
    at ion_range_sliders.html:26
```

**Comment by bryevdv** [comment]
@Karel-van-de-Plassche FYI just to set expectations, I am dealing with a family medical situation currently, it may be a few weeks before I can really dive into things. That said, I do think offhand that it would be appropriate and preferable for any slider to inherit from `AbstractSlider`. The message you are currently seeing indicates that the model is not defined and registered, which could be the case if the bundle is not loaded. There are ways to explicitly configure resources to load bundles AFAIK, @mattpap can comment more.

**Comment by Karel-van-de-Plassche** [comment]
> That said, I do think offhand that it would be appropriate and preferable for any slider to inherit from `AbstractSlider`

I'm writing everything up so that an eventual move to `AbstractSlider` should be straightforward. While I in principle agree with your statement, `AbstractSlider` currently includes some `nouislider` specific data which I didn't want to mess with, which could of course be moved to its own file later.

**Comment by Karel-van-de-Plassche** [comment]
Actually started from scratch to learn some more TypeScript, you can find my trials here: https://github.com/Karel-van-de-Plassche/bokehTypescriptTrials

A lot of the troubles were because of missing type definitions, and a misnamed and wrong type package `@types/ion.rangeslider`. I've created by own typedef in https://github.com/Karel-van-de-Plassche/types-ion-rangeslider.

I got the example working again in TypeScript by forcing the `__implementation__`, `__javascript__` and `__css__` attributes in `ion_range_slider.py`. I guess this is not a permanent solution though, so waiting on comments from @mattpap

**Comment by Karel-van-de-Plassche** [comment]
Created a stand-alone bundle for bokeh here: https://github.com/Karel-van-de-Plassche/bokeh-ion-rangeslider. There is more formatting to be done, but I can easily import it in random projects with `from bokeh_ion_rangeslider import *`. I'm still working on trying to integrate it in native bokeh.
![image](https://user-images.githubusercontent.com/6404167/39667947-97866efe-50c1-11e8-92fb-d376c250087f.png)

**Comment by Karel-van-de-Plassche** [comment]
Submitted the ion.RangeSlider types to DefinitelyTyped https://github.com/DefinitelyTyped/DefinitelyTyped/pull/25577

**Comment by Karel-van-de-Plassche** [comment]
Fixed a lot of bugs and added extra example.
![image](https://user-images.githubusercontent.com/6404167/39822730-956ce73c-53ab-11e8-896f-1f9100110172.png)
Integration in bokeh still needs some work. Most notably, there are some type collisions between `abstract_slider.ts` and `ion_range_slider.ts`, and I don't know the correct course of action to solving this. @bryevdv @mattpap?
- abstract_slider.values is number[], while ionRangeSlider.values can be number[] and string[]
- abstract_slider onChange event is `(_, __, number[]) -> void`, while ionRangeSliders is `(IonRangeSliderEvent) -> void`

Also, some TypeScript errors in AbstractSlider and ionRangeSlider:
- Some implicit any's in the anonymous functions `(_: any, __: any, values: any) => void`
- Some unread variables (`'data' is declared but its value is never read.`)

And a folder structure one:
- `src/lib/models/widgets/contrib/index.ts(1,15): error TS2307: Cannot find module './ionRangeSlider'`

**Comment by duynguyen2411** [comment]
Hello i'm using Bokeh to developpe a GUI. I want to use Ion.RangeSlider but i don't how i can install ? Thanks so much if you can help me.

**Comment by bryevdv** [comment]
We have still not solidified anything around distribution of extensions. You will have to directly copy/use the code from the user guide example:

https://bokeh.pydata.org/en/latest/docs/user_guide/extensions_gallery/widget.html#userguide-extensions-examples-widget

**Comment by duynguyen2411** [comment]
Thanks for your answer. Did you create a multi-range slider for Bokeh? I don't know JavaScripts so it's so difficult with me.

**Comment by Karel-van-de-Plassche** [comment]
I have to add that unfortunately my slider implementation based on this example broke from `bokeh==1.0.5 `-> `bokeh==1.1.0`

**Comment by bryevdv** [comment]
> PS. Looking at the example, that implementation inherits from InputWidget and InputWidgetView, not AbstractSlider and AbstractSliderView as we discussed a while ago. Did your opinion on this change @bryevdv? I'd like to make my slider compatible with the most recent bokeh again.

I'm afraid I don't recall the discussion, do you have a link to it? In any case, I haven't done any work on this at all, @mattpap can comment on all the things that happened in 1.1

**Comment by Karel-van-de-Plassche** [comment]
The changes to `AbstractSlider` seem significant, and to make my sliders work again I need quite some more work than I expected, not helped by the fact that I've never really coded in JS/TS before. I think I can make it work, but it ain't gonna be pretty. A lot of methods in `AbstractSlider` look mode for `noUiSlider` specifically (not strange, as it is the only slider in bokeh), so it might make more sense to subclass `ControlView` after all. Significant differences:

- `value` can be `number`, `number[]`, `date` or `date[]`. for ionRangeSlider values can be `string[]`, `string` too
  - `_slide` and `_throttle` need special handling because of the strings
- `connect_signals` calls `noUiSlider`'s `update`, so not general
- `_set_bar_color` is `noUiSlider` specific
- `AbstractSlider` has a custom keypress handler, number prettifier and title. `ionRangeSlider` has it build in
- `render` calls `noUiSlider` initialization
- `ionRangeSlider` only has a horizontal mode

Not sure how `tooltips` is supposed to work.

So in the end, I can re-use almost no methods of `AbstractSlider`. Maybe it makes more sense to just subclass `ControlView` instead. Thoughts @mattpap?

**Comment by Karel-van-de-Plassche** [comment]
I have build the slider to work with 1.1.0 and newer again: https://github.com/Karel-van-de-Plassche/bokeh-ion-rangeslider/tree/bokeh-1.1.0

**Comment by duynguyen2411** [comment]
I try to use your new slider But there is an error :

Compilation failed:

ion_range_slider.ts:226:16 - error TS2339: Property 'value_throttled' does not exist on type 'IonRangeSlider'.

226     this.model.value_throttled = this.model.value

**Comment by bryevdv** [comment]
> ion_range_slider.ts:226:16 - error TS2339: Property 'value_throttled' does not exist on type 'IonRangeSlider'.

`value_throttled` is new as of the very last release. Your installed Bokeh version is to old to use this code.

**Comment by duynguyen2411** [comment]
Not work with bokeh 1.1.0 but it works with 1.2.0

**Comment by bryevdv** [comment]
1.2 was the very last release, so that is when `value_throttled` was added. It did not exist in previous releases (hence the error)

**Comment by Karel-van-de-Plassche** [comment]
My mistake, indeed, I only tested it for the latest bokeh, so the branch
name is a bit of a misnomer

**Comment by Karel-van-de-Plassche** [comment]
Ran into this issue again. Working on bokeh-2.0.2 conversion here: https://github.com/Karel-van-de-Plassche/bokeh-ion-rangeslider/tree/bokeh-2.0.2 Maybe good to think about #7853 and #7894 again?
