### ISSUE TITLE
autoload_server() doc embedding example fails

### ISSUE THREAD

**Issue by davidljung** [bokeh/bokeh#1379]
On the embedding doc page: http://bokeh.pydata.org/docs/user_guide/embedding.html
It provides a code snippet:
```
from bokeh.plotting import circle
from bokeh.embed import autoload_server
from bokeh.session import Session

session = Session()

plot = circle([1,2], [3,4])

script = autoload_server(plot, session)
```

However, that snippet fails with the error:
```
..site-packages\bokeh\embed.pyc in autoload_server(plot_object, session)
    197         modelid = plot_object._id,
    198         root_url = resources.root_url,
--> 199         docid =  session.docid,
    200         docapikey = session.apikey,
    201         loglevel = resources.log_level,

AttributeError: 'Session' object has no attribute 'docid' 
```

In my experimentation, I can't figure out any way to create the Session object that makes this work.  Also, it doesn't seem to be possible to use with Charts without fetching the plot object out of the chart in a non-standard way.
Thanks.
 (v 0.6.1; server running on standard localhost:5006 with default Shelve backend)

**Comment by bryevdv** [comment]
Hi @davidljung I am sorry this discussion go lost in the holidays and two releases. Did you find answers to any of these questions? Which ones remain? @fpliger can you comment on the charts question.

**Comment by birdsarah** [comment]
@davidljung in case you didn't have answers to the questions, working with the latest bokeh (currently 0.8.1) I think the following is correct:

Example of using a chart, storing it on the server, and getting the autoload:
````python
from bokeh.embed import autoload_server
from bokeh.session import Session
from bokeh.document import Document
from bokeh.charts import Dot
# Setup the session
document = Document()
session = Session(root_url='http://my.bokeh.server:5000/', load_from_config=False)
session.use_doc('population_reveal')
session.load_document(document)
# Make the chart
dot = Dot([[1,2], [3,4]]) 
# Attach the chart to the document
document.clear()  # Semi-optional - see below
document.add(dot)
# Put it on the server
session.store_document(document)
script = autoload_server(dot, session)
````
If you don't use the line `document.clear()` you will see, on the server, that there are multiple copies of your chart building up.

However, the script just gives you the one chart. So.....that's interesting.   I use `document.clear()` so I am sure what's going on.

`session.userinfo` is a dictionary which has a list of docs on it. But I'm not sure how to use this usefully.

So I have been re-creating documents each time I need one, but then using document.clear() so I don't have lots of things on the server. (Of course sometimes I want multiple instances, and in that case I give a uid to `use_doc`)

Don't know if any of this is any use, I'm hoping it's all accurate, at least.

**Comment by fpliger** [comment]
thanks @birdsarah  for following up on this, specially bringing an example of `charts` and `bokeh-server` integration (we don't have many available yet).

IIRC we have had the discussion regarding a monkeypatch solution that could make the previous versions of `bokeh.charts` work with bokeh server (or embedding). The issue was that `charts` didn't inherit from `Plot` like in >`0.8` version and had an underlying `.chart.plot` that could have been used as gate to retrieve the actual plot.. Luckily all that is gone now and you can use the Charts directly with bokeh-server or other places.

@davidljung I remember some discussions regarding the other bokeh-server quetions happening elsewhere too but wasn't able to find them. Can you check if my memory is tricking me or, most important, if you've got the answers you needed?
