### ISSUE TITLE
bokeh-plot directive incomptable with sphinx 1.7

### ISSUE THREAD

**Issue by lgarcin** [bokeh/bokeh#7520]
I get the following error when I build html with sphinx1.7 and bokeh 0.12.14

`Exception occurred:                                                                                                                           
  File "C:\Users\laure\AppData\Local\Programs\Python\Python36\lib\site-packages\bokeh\sphinxext\bokeh_plot.py", line 295, in build_finished   
    files_iter = app.status_iterator(sorted(files),                                                                                           
AttributeError: 'Sphinx' object has no attribute 'status_iterator'`

Indeed, `Sphinx.status_iterator` is removed from sphinx1.7 and should be replaced by `sphinx.util:status_iterator`.

**Comment by bryevdv** [comment]
@lgarcin There are further changes besides this required to get the Bokeh docs build working with Sphinx > 1.5 which is why it has not been done yet. However, if this change alone is sufficient to get things working for you, I'd happily merge a more focused PR that does just this. (I am in the middle of moving across the country, so it will happen much faster if you submit the PR).
