### PR TITLE
Bryanv/01215 docs

### LINKED ISSUE #7516: Update examples and add documentation for Selection model
The new Selection model which represents data sources' selections and inspections was added in [PR 7261](https://github.com/bokeh/bokeh/pull/7261). This issue is for updating examples, adding documentation, and potentially adding examples.

One example that can be added is how to set a selection on a network graph plot and then apply a policy. This would, for example, allow someone to set a selection based on node indices and then have the linked edges highlighted through the NodesAndLinkedEdges policy. 

- [x] update all examples to use new `Selection` model
- [ ] expand docs around the `Selection` model
- [x] Add a migration section to release notes (programmatically updated selections will break)

### LINKED ISSUE #7520: bokeh-plot directive incomptable with sphinx 1.7
I get the following error when I build html with sphinx1.7 and bokeh 0.12.14

`Exception occurred:                                                                                                                           
  File "C:\Users\laure\AppData\Local\Programs\Python\Python36\lib\site-packages\bokeh\sphinxext\bokeh_plot.py", line 295, in build_finished   
    files_iter = app.status_iterator(sorted(files),                                                                                           
AttributeError: 'Sphinx' object has no attribute 'status_iterator'`

Indeed, `Sphinx.status_iterator` is removed from sphinx1.7 and should be replaced by `sphinx.util:status_iterator`.

### PR DESCRIPTION
**Pull request by bryevdv**
Collects several doc edits, updates, and fixes:

* updates to work with Sphinx >= 1.6
* removes/re-consolidates small user guide sections to shorten TOC
* remove backbone mentions
* remove cruft images
* updates for content (geo, selections, concepts)
* NF sponsorship copy

issues: fixes #7520 fixes #7516

### CODE REVIEW

File: sphinx/source/docs/user_guide/examples/extensions_example_wrapping.py [hunk 1]
```diff
@@ -91,7 +86,7 @@
       })
     return data
 
-# We must also create a corresponding JavaScript Backbone model sublcass to
+# We must also create a corresponding JavaScript BokehJS model sublcass to
```
Comment (mattpap) [inline sphinx/source/docs/user_guide/examples/extensions_example_wrapping.py]: `sublcass`

**Comment by bryevdv** [comment]
I think maybe this is enough for this PR. I will merge when green then cut a dev build
