### ISSUE TITLE
Deploying Holoviews App Using Bokeh

### ISSUE THREAD

**Issue by samrogers226** [bokeh/bokeh#6973]
Bokeh versions 0.12.7+ (works with Bokeh versions < 0.12.7)
Holoviews 1.8.4
Tornado 4.5.2
Python 3.5
Mac OS 10.12.6
Google Chrome 61.0.3163.91

When running:
```
from holoviews import renderer, extension

extension('bokeh')
render = renderer('bokeh')

server = render.app(some_holoviews_plot, show=show, new_window=new_window)
```
a new window should open in your browser and return a plot

However, the following error appears:
```
Traceback (most recent call last):
    server = render.app(some_holoviews_plot, show=show, new_window=new_window)
  File “/anaconda/envs/total-home/lib/python3.5/site-packages/holoviews/plotting/bokeh/renderer.py”, line 169, in app
    server = Server({‘/’: app}, port=0, loop=loop, **opts)
  File “/anaconda/envs/total-home/lib/python3.5/site-packages/bokeh/server/server.py”, line 371, in __init__
    tornado_app = BokehTornado(applications, extra_websocket_origins=extra_websocket_origins, prefix=self.prefix, **kwargs)
TypeError: __init__() got an unexpected keyword argument ‘loop’
```
It appears that there is an issue with the naming of "loop" vs. "io_loop" and how it is passed between functions within the packages. Bokeh Versions <0.12.7 do not experience this issue. 

A fix would be appreciated.

**Comment by philippjfr** [comment]
@samrogers226 Would you mind reopening this issue in the HoloViews repo? There have been some changes in the bokeh API recently and we haven't quite caught up yet, but that's something for us to fix in HoloViews.
