### PR TITLE
Update CONTRIBUTING.md

### LINKED ISSUE #3947: CONTRIBUTING.md Code Issue
The below line found in the contributing section does not work on my version - bokeh (0.11.1) with Python 3.
```
python -c "import bokeh; print(bokeh.print_versions())"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: module 'bokeh' has no attribute 'print_versions'
```

### PR DESCRIPTION
**Pull request by bryevdv**
issues: closes #3947

### CODE REVIEW

**Comment by bryevdv** [comment]
Docs only, not re-running spurious test failures.
