### ISSUE TITLE
Add a polyfill for Math.log1p() that's not supported by IE

### ISSUE THREAD

**Issue by mattpap** [bokeh/bokeh#5248]
Also examples, like `plotting/file/texas` fail in phantomjs. The error is `undefined is not a function`. This was introduced in PR #4490.
