### ISSUE TITLE
bokeh docs heatmap example broken

### ISSUE THREAD

**Issue by jdimatteo** [bokeh/bokeh#4743]
When running the example at http://bokeh.pydata.org/en/0.12.0/docs/reference/charts.html#heatmap with bokeh 0.12.0, an error occurs, e.g.

```
Traceback (most recent call last):
  File "heatmap.py", line 16, in <module>
    p = HeatMap(df, title='Fruits')
  File "/usr/local/lib/python2.7/dist-packages/bokeh/charts/builders/heatmap_builder.py", line 92, in HeatMap
    chart = create_and_build(HeatMapBuilder, data, xgrid=xgrid, ygrid=ygrid, **kw)
  File "/usr/local/lib/python2.7/dist-packages/bokeh/charts/builder.py", line 73, in create_and_build
    chart.add_builder(builder)
  File "/usr/local/lib/python2.7/dist-packages/bokeh/charts/chart.py", line 171, in add_builder
    builder.create(self)
  File "/usr/local/lib/python2.7/dist-packages/bokeh/charts/builder.py", line 531, in create
    self.process_data()
  File "/usr/local/lib/python2.7/dist-packages/bokeh/charts/builders/heatmap_builder.py", line 172, in process_data
    columns=self.values.selection)
  File "/usr/local/lib/python2.7/dist-packages/bokeh/charts/attributes.py", line 198, in setup
    self.attr_map = self._create_attr_map(self.data.to_df(), self.columns)
  File "/usr/local/lib/python2.7/dist-packages/bokeh/charts/attributes.py", line 168, in _create_attr_map
    self._generate_items(df, columns)
  File "/usr/local/lib/python2.7/dist-packages/bokeh/charts/attributes.py", line 249, in _generate_items
    bins=len(self.iterable), aggregate=False)
  File "/usr/local/lib/python2.7/dist-packages/bokeh/charts/stats.py", line 311, in __init__
    super(BinnedStat, self).__init__(**properties)
  File "/usr/local/lib/python2.7/dist-packages/bokeh/charts/stats.py", line 56, in __init__
    self._refresh()
  File "/usr/local/lib/python2.7/dist-packages/bokeh/charts/stats.py", line 62, in _refresh
    self.calculate()
  File "/usr/local/lib/python2.7/dist-packages/bokeh/charts/stats.py", line 365, in calculate
    self.source.add(binned.tolist(), name=self.bin_column)
AttributeError: 'Categorical' object has no attribute 'tolist'
```

**Comment by jdimatteo** [comment]
I'm just trying to get started displaying a numpy 2d array as a heatmap (similar to how I can pass an ndarray to matplotlib.pyplot imshow).  If someone could post any working heatmap example, or suggest a version to downgrade to, I'd appreciate it, thanks.

**Comment by bryevdv** [comment]
I just tried that code verbatim and it is working as expected (the plots are actually generated directly from the associated code, so the mere presence of a plot at all means it is working in some way). So, can you provide more information about your system and versions, etc.

**Comment by bryevdv** [comment]
are you certain the python you are running is the python that has `0.12` installed, for instance? That is the first thing I would check.

**Comment by bryevdv** [comment]
also works with `0.11`. Fails with old API in `0.10` and `0.9.3` but with a different message. So, maybe a pandas change? Definitely need your system configuration, versions, etc to reproduce.

**Comment by jdimatteo** [comment]
I'm certain I'm using 0.12, but I'm using pandas version 0.13.1.  I'm upgrading pandas to 0.18 now to see if that fixes it.

**Comment by jdimatteo** [comment]
Upgrading pandas to 0.18.1 fixed the problem.  Maybe we should update http://bokeh.pydata.org/en/latest/docs/installation.html to suggest a pandas version?

Feel free to just close this issue, sorry if this turned out to be more of a support issue not appropriate for a ticket.

Thanks

**Comment by bryevdv** [comment]
Sometimes it's hard to know up front. :) I'd definitely amenable to suggesting a min version. If you have the time to check a few earlier pandas versions to try and see what a "minimum" min version is, that would definitely be helpful.

**Comment by jdramirez** [comment]
I have the same error when I work with Ipython. However I have pandas 0.18.1

**Comment by xysmas** [comment]
I also have the same error within the Jupyter Notebook environment. 

It's a fresh conda environment, python 2.7. Same error on 3.5. 

```.python
import bokeh
import pandas as pd
from bokeh.charts import HeatMap, show, output_notebook
bokeh.__version__
pd.__version__

output_notebook()


# (dict, OrderedDict, lists, arrays and DataFrames are valid inputs)
data = {'fruit': ['apples']*3 + ['bananas']*3 + ['pears']*3,
        'fruit_count': [4, 5, 8, 1, 2, 4, 6, 5, 4],
        'sample': [1, 2, 3]*3}

hm = HeatMap(data, x='fruit', y='sample', values='fruit_count',
             title='Fruits', stat=None)

show(hm)
```

```.python
0.12.1'
Out[314]:
u'0.18.1'
 BokehJS successfully loaded

 
 
 
 
 
 ---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-314-a5d4379b67fb> in <module>()
     16              title='Fruits', stat=None)
     17 
---> 18 show(hm)

/home/agonzales/anaconda3/envs/keras_converter/lib/python2.7/site-packages/bokeh/io.pyc in show(obj, browser, new)
    302     if obj not in _state.document.roots:
    303         _state.document.add_root(obj)
--> 304     return _show_with_state(obj, _state, browser, new)
    305 
    306 

/home/agonzales/anaconda3/envs/keras_converter/lib/python2.7/site-packages/bokeh/io.pyc in _show_with_state(obj, state, browser, new)
    312 
    313     if state.notebook:
--> 314         comms_handle = _show_notebook_with_state(obj, state)
    315         shown = True
    316 

/home/agonzales/anaconda3/envs/keras_converter/lib/python2.7/site-packages/bokeh/io.pyc in _show_notebook_with_state(obj, state)
    352         comms_target = make_id()
    353         publish_display_data({'text/html': notebook_div(obj, comms_target)})
--> 354         handle = _CommsHandle(get_comms(comms_target), state.document, state.document.to_json())
    355         state.last_comms_handle = handle
    356         return handle

/home/agonzales/anaconda3/envs/keras_converter/lib/python2.7/site-packages/bokeh/document.pyc in to_json(self)
    818         # this is a total hack to go via a string, needed because
    819         # our BokehJSONEncoder goes straight to a string.
--> 820         doc_json = self.to_json_string()
    821         return loads(doc_json)
    822 

/home/agonzales/anaconda3/envs/keras_converter/lib/python2.7/site-packages/bokeh/document.pyc in to_json_string(self, indent)
    806             'roots' : {
    807                 'root_ids' : root_ids,
--> 808                 'references' : self._references_json(root_references)
    809             },
    810             'version' : __version__

/home/agonzales/anaconda3/envs/keras_converter/lib/python2.7/site-packages/bokeh/document.pyc in _references_json(cls, references)
    617         for r in references:
    618             ref = r.ref
--> 619             ref['attributes'] = r._to_json_like(include_defaults=False)
    620             references_json.append(ref)
    621 

/home/agonzales/anaconda3/envs/keras_converter/lib/python2.7/site-packages/bokeh/models/sources.pyc in _to_json_like(self, include_defaults)
    170         attrs = super(ColumnDataSource, self)._to_json_like(include_defaults=include_defaults)
    171         if 'data' in attrs:
--> 172             attrs['data'] = transform_column_source_data(attrs['data'])
    173         return attrs
    174 

/home/agonzales/anaconda3/envs/keras_converter/lib/python2.7/site-packages/bokeh/util/serialization.pyc in transform_column_source_data(data)
    138     for key in iterkeys(data):
    139         if pd and isinstance(data[key], (pd.Series, pd.Index)):
--> 140             data_copy[key] = transform_series(data[key])
    141         elif isinstance(data[key], np.ndarray):
    142             data_copy[key] = transform_array(data[key])

/home/agonzales/anaconda3/envs/keras_converter/lib/python2.7/site-packages/bokeh/util/serialization.pyc in transform_series(obj)
     50     """
     51     vals = obj.values
---> 52     return transform_array(vals)
     53 
     54 def transform_array(obj):

/home/agonzales/anaconda3/envs/keras_converter/lib/python2.7/site-packages/bokeh/util/serialization.pyc in transform_array(obj)
     85     elif obj.dtype.kind in ('u', 'i', 'f'):
     86         return transform_numerical_array(obj)
---> 87     return obj.tolist()
     88 
     89 def transform_numerical_array(obj):

AttributeError: 'Categorical' object has no attribute 'tolist'
```

**Comment by duncangh** [comment]
I have a similar issue running Jupyter Notebook heat map example. 

pandas='0.20.1'
bokeh='0.12.5'


from bokeh.charts import HeatMap, output_file, show

# (dict, OrderedDict, lists, arrays and DataFrames are valid inputs)
dataa = {'fruit': ['apples']*3 + ['bananas']*3 + ['pears']*3,
        'fruit_count': [4, 5, 8, 1, 2, 4, 6, 5, 4],
        'sample': [1, 2, 3]*3}

hm = HeatMap(dataa, x='fruit', y='sample', values='fruit_count',
             title='Fruits', stat=None)

output_file('heatmap.html')
show(hm)

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-56-e2abcb05d9e4> in <module>()
      7 
      8 hm = HeatMap(dataa, x='fruit', y='sample', values='fruit_count',
----> 9              title='Fruits', stat=None)
     10 
     11 output_file('heatmap.html')

/usr/local/lib/python3.5/site-packages/bokeh/charts/builders/heatmap_builder.py in HeatMap(data, x, y, values, stat, xgrid, ygrid, hover_tool, hover_text, **kw)
     90     kw['values'] = values
     91     kw['stat'] = stat
---> 92     chart = create_and_build(HeatMapBuilder, data, xgrid=xgrid, ygrid=ygrid, **kw)
     93 
     94     if hover_tool:

/usr/local/lib/python3.5/site-packages/bokeh/charts/builder.py in create_and_build(builder_class, *data, **kws)
     54     chart_kws = {k: v for k, v in kws.items() if k not in builder_props}
     55     chart = Chart(**chart_kws)
---> 56     chart.add_builder(builder)
     57     chart.start_plot()
     58 

/usr/local/lib/python3.5/site-packages/bokeh/charts/chart.py in add_builder(self, builder)
    151     def add_builder(self, builder):
    152         self._builders.append(builder)
--> 153         builder.create(self)
    154 
    155     def add_ranges(self, dim, range):

/usr/local/lib/python3.5/site-packages/bokeh/charts/builder.py in create(self, chart)
    504         # call methods that allow customized setup by subclasses
    505         self.setup()
--> 506         self.process_data()
    507 
    508         # create and add renderers to chart

/usr/local/lib/python3.5/site-packages/bokeh/charts/builders/heatmap_builder.py in process_data(self)
    170         # color by the values selection
    171         self.attributes['color'].setup(data=self._data.source,
--> 172                                        columns=self.values.selection)
    173         self.attributes['color'].add_bin_labels(self._data)
    174 

/usr/local/lib/python3.5/site-packages/bokeh/charts/attributes.py in setup(self, data, columns)
    200 
    201         if self.columns is not None and self.data is not None:
--> 202             self.attr_map = self._create_attr_map(self.data.to_df(), self.columns)
    203 
    204     def update_data(self, data):

/usr/local/lib/python3.5/site-packages/bokeh/charts/attributes.py in _create_attr_map(self, df, columns)
    170 
    171         if df is not None and columns is not None:
--> 172             self._generate_items(df, columns)
    173 
    174         iterable = self._setup_iterable()

/usr/local/lib/python3.5/site-packages/bokeh/charts/attributes.py in _generate_items(self, df, columns)
    251 
    252                 self.bins = Bins(source=ColumnDataSource(df), column=columns[0],
--> 253                                  bins=len(self.iterable), aggregate=False)
    254 
    255                 if self.sort:

/usr/local/lib/python3.5/site-packages/bokeh/charts/stats.py in __init__(self, values, column, bins, stat, source, **properties)
    308         properties['source'] = source
    309         self._bins = bins
--> 310         super(BinnedStat, self).__init__(**properties)
    311 
    312 

/usr/local/lib/python3.5/site-packages/bokeh/charts/stats.py in __init__(self, **properties)
     53 
     54         super(Stat, self).__init__(**properties)
---> 55         self._refresh()
     56 
     57     def _refresh(self):

/usr/local/lib/python3.5/site-packages/bokeh/charts/stats.py in _refresh(self)
     59         if self.get_data() is not None:
     60             self.update()
---> 61             self.calculate()
     62 
     63     def set_data(self, data, column=None):

/usr/local/lib/python3.5/site-packages/bokeh/charts/stats.py in calculate(self)
    369         for name, group in df.groupby(self.bin_column):
    370             bin_models.append(Bin(bin_label=name, values=group[self.column],
--> 371                                   stat=self.stat))
    372 
    373         self.bins = bin_models

/usr/local/lib/python3.5/site-packages/bokeh/charts/stats.py in __init__(self, bin_label, values, source, **properties)
    175         properties['label'] = bin_label
    176 
--> 177         bounds = self.process_bounds(bin_label)
    178 
    179         starts, stops = zip(*bounds)

/usr/local/lib/python3.5/site-packages/bokeh/charts/stats.py in process_bounds(self, bin_label)
    205     def process_bounds(self, bin_label):
    206         if isinstance(bin_label, list):
--> 207             return [self.binstr_to_list(dim) for dim in bin_label]
    208         else:
    209             return [self.binstr_to_list(bin_label)]

/usr/local/lib/python3.5/site-packages/bokeh/charts/stats.py in <listcomp>(.0)
    205     def process_bounds(self, bin_label):
    206         if isinstance(bin_label, list):
--> 207             return [self.binstr_to_list(dim) for dim in bin_label]
    208         else:
    209             return [self.binstr_to_list(bin_label)]

/usr/local/lib/python3.5/site-packages/bokeh/charts/stats.py in binstr_to_list(bins)
    197     def binstr_to_list(bins):
    198         """Produce a consistent display of a bin of data."""
--> 199         value_chunks = bins.split(',')
    200         value_chunks = [val.replace('[', '').replace(']', '').replace('(', '').replace(')', '') for val in value_chunks]
    201         bin_values = [float(value) for value in value_chunks]

AttributeError: 'pandas._libs.interval.Interval' object has no attribute 'split'

**Comment by bryevdv** [comment]
@duncangh bokeh.charts has moved to a new separate repo and project all issues for it should go here https://github.com/bokeh/bkcharts
