### PR TITLE
Upgrade typescript to 2.4 and ts-node to 3.1

### LINKED ISSUE #6395: Investigate errors with ts-node 4.0.5
Follow up on PR #6392. For now ts-node was pinned, but we need figure out what's actually wrong with the current setup.

### LINKED ISSUE #6549: upgrading to typescript=2.4.1 breaks gulp build task
upgrading to typescript=2.4.1 breaks gulp build task

```
+node_modules/.bin/gulp build
⨯ Unable to compile TypeScript
Cannot find type definition file for 'browserify'. (2688)
Cannot find type definition file for 'chai'. (2688)
Cannot find type definition file for 'chalk'. (2688)
Cannot find type definition file for 'del'. (2688)
Cannot find type definition file for 'event-stream'. (2688)
Cannot find type definition file for 'glob'. (2688)
Cannot find type definition file for 'gulp'. (2688)
Cannot find type definition file for 'gulp-insert'. (2688)
Cannot find type definition file for 'gulp-less'. (2688)
Cannot find type definition file for 'gulp-rename'. (2688)
Cannot find type definition file for 'gulp-sourcemaps'. (2688)
Cannot find type definition file for 'gulp-task-listing'. (2688)
Cannot find type definition file for 'gulp-util'. (2688)
```

bokeh 0.12.7dev3

ping @mattpap

### PR DESCRIPTION
**Pull request by mattpap**
ts-node needed to be upgraded, because it didn't implement appropriate interfaces when working with TS 2.4, which resulted in ts-node not being able to resolve modules. This works locally, but lets see if this works on travis ci as well, because previously had to pin ts-node ( #6395). 

fixes #6549 
fixes #6395

### CODE REVIEW

**Comment by mattpap** [comment]
I will go ahead and merge this as it's required in other PRs.
